### ISSUE TITLE
501 gateway error

### ISSUE THREAD

**Issue by kngzmi** [simonfarah/tiktok-bot#114]
When i run the command (python bot.py), it opens a google browser different from the one im using. When i try to log in in that browser, it shows 
"This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in."
So i suspect it might be a non secure browser, which ultimately leads to the 502 Gateway Error 
Edit: Also, i tried using a VPN and it loaded. But it goes on a loop everytime i click the captcha.

**Comment by simonfarah** [comment]
When the new browser tab opens, you must leave it intact unless requested by the bot. I suppose you're using it, right?

**Comment by kngzmi** [comment]
I do leave it intact, yes. The issue is, the google chrome it's using is different from my google chrome, if that makes sense. I cant even merge the tabs from my google to that google. Maybe zefoy is the problem? i tried to open zefoy on my original google chrome and after i complete the captcha it just shows a 502 gateway error. If i do it in the google chrome the bot opened, the captcha just loops.

**Comment by simonfarah** [comment]
Can I have some screen recording please to better understand from where the issue comes from and work on a solution

**Comment by Ponk445** [comment]
@simonfarah look, the owner of zefoy connected to cloudflare/set toe cloudflare mode to "im being attacked". this means that your website is (example) dos/ddos -ed. or if, like this, there are bots.
i think that it was activated because of, yes, bots like this.
now, the captcha checks multiple things... @kngzmi  and the thing triggering the captcha to the loop, is that the chrome browser is opened as an "automated browser" (stands at the top of bot opened chrome) this also answers kngzmi`s question, it is a browser window, that`s made to be controlled/is for bots that will be used to control the window, using only code that points to the buttons(i think) if you use it with normal browser, it won`t work.
whatever, to simonfarah: you will have to add a cloudflare bypass tool, or wait for the owner to deactivare the mode, what i dont think the owner will do. there is a bypass at a different bot which i cant find the link of anymore, sorry.
i didnt give anything about my grammer here, so dont say anything.

**Comment by simonfarah** [comment]
> @simonfarah look, the owner of zefoy connected to cloudflare/set toe cloudflare mode to "im being attacked". this means that your website is (example) dos/ddos -ed. or if, like this, there are bots. i think that it was activated because of, yes, bots like this. now, the captcha checks multiple things... @kngzmi and the thing triggering the captcha to the loop, is that the chrome browser is opened as an "automated browser" (stands at the top of bot opened chrome) this also answers kngzmi s question, it is a browser window, thats made to be controlled/is for bots that will be used to control the window, using only code that points to the buttons(i think) if you use it with normal browser, it won`t work. whatever, to simonfarah: you will have to add a cloudflare bypass tool, or wait for the owner to deactivare the mode, what i dont think the owner will do. there is a bypass at a different bot which i cant find the link of anymore, sorry. i didnt give anything about my grammer here, so dont say anything.

That's what I also noticed. Thank you! Will be working on a fix soon.

**Comment by simonfarah** [comment]
A new version has been pushed and should fix all raised bugs. Please try it and feel free to reopen an issue for any other bugs.
