### ISSUE TITLE
Only works for first view

### ISSUE THREAD

**Issue by Bronac** [simonfarah/TikTok-Bot#2]
It only works for the first time. Then afterwards it says the error:

[9340:30160:1104/094115.911:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by simonfarah** [comment]
This error "[9340:30160:1104/094115.911:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is..." comes from the chromedriver and can be completely ignored, it doesn't affect anything. And to get the views for the second time the bot waits 10min to redo the loop, this wait time is set by zefoy.com to prevent abuse. So if you wait 10 min, the bot will continue its work. Please try it and let me know.

**Comment by Bronac** [comment]
Yep sorry just realised this thats working. But another issue currently the auto views is the only one thats working. I tried auto shares and auto comment likes but those searches the link and does not press the button. It says error trying again and it just loops. Please look into this.

**Comment by simonfarah** [comment]
Unfortunately the error you are talking about is something I can't control. This happens when the zefoy server is not serving shares or likes... You will most likely see a "soon will be update" message under the service you are trying to get. In this case, you must wait till this service is made available again by zefoy. Hope this helped and thank you for your questions!
