### ISSUE TITLE
WebDriverException

### ISSUE THREAD

**Issue by brandonfelt017** [simonfarah/TikTok-Bot#46]
I'm on MacOS, running the script. I was running it successfully earlier in the week and now this issue started happening. Shortly after choosing likes or views (any of the options cause the issue) the browser will boot up. Once I finish the captcha it will load the next page and then shortly thereafter the script crashes. The error given is in the image below.

![Screen Shot 2022-07-01 at 3 15 22 PM](https://user-images.githubusercontent.com/108551920/176962824-082ed763-f1ce-4ee9-bcab-01835a0c69a7.png)

OS and chrome versions
 - MacOS 12.2
 - Chrome Version 103.0.5060.53

**Comment by simonfarah** [comment]
Hello! This is a Chrome version 103 problem and this issue has been raised in the Chromium and in the Selenium community. However, Selenium community has closed the issue because the issue is related to to the Chrome team.

Until this bug is fixed try to downgrade Chrome browser to v102 and download Selenium Chrome Driver v102 and try to run the script, as this issue is happing in version 103.
